#!/usr/bin/bash

PKG_NAME="gcc"
PKG_VERSION="15.2.0"
PKG_URL="https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.xz"
PKG_MD5="b861b092bf1af683c46a8aa2e689a6fd"

rm -rf $PKG_NAME-$PKG_VERSION

if [[ -f "$PKG_NAME-$PKG_VERSION.tar.xz" ]]; then
   TEST_MD5=$(md5sum "$PKG_NAME-$PKG_VERSION.tar.xz" | awk '{print $1}')
   if [[ "$TEST_MD5" == "$PKG_MD5" ]]; then
      echo "md5 check pass"
   else
      echo "md5 dont match"
      wget $PKG_URL
      if [[ "$TEST_MD5" == "$PKG_MD5" ]]; then
      echo "md5 check pass"
      fi
    fi
else
    "downloading $PKG_NAME source code"
     wget $PKG_URL
     TEST_MD5=$(md5sum "$PKG_NAME-$PKG_VERSION.tar.xz" | awk '{print $1}')
     if [[ "$TEST_MD5" == "$PKG_MD5" ]]; then
     echo "md5 check pass"
fi

tar xf $PKG_NAME-$PKG_VERSION.tar.xz
cd $PKG_NAME-$PKG_VERSION

case $(uname -m) in
x86_64)
sed -e '/m64=/s/lib64/lib/' \
-i.orig gcc/config/i386/t-linux64
;;
esac

mkdir -p $PKG_NAME-build && cd $PKG_NAME-build

echo "applying settings for build"
../configure --prefix=/usr            \
LD=ld                    \
--enable-languages=c,c++ \
--enable-default-pie     \
--enable-default-ssp     \
--enable-host-pie        \
--disable-multilib       \
--disable-bootstrap      \
--disable-fixincludes    \
--with-system-zlib  && make -j$(nproc)

make install
chown -v -R root:root \
/usr/lib/gcc/$(gcc -dumpmachine)/15.2.0/include{,-fixed}
ln -svr /usr/bin/cpp /usr/lib
ln -sv gcc.1 /usr/share/man/man1/cc.1
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/15.2.0/liblto_plugin.so \
        /usr/lib/bfd-plugins/
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
